---
title: "Weight Tracker"
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    orientation: rows
  source_code: embed
---
  
```{r main calculations}
# import libraries
library(curl)           # needed for fread to call in github data files
library(dplyr)          # joining tables
library(shiny)          # shiny framework
library(ggplot2)        # line chart viz
library(data.table)     # data munging
library(flexdashboard)  # dashboard framework
library(imputeTS)       # TS imputation

# read data from github ##########################################################################
mp <- fread("https://raw.githubusercontent.com/johnsug/wt/master/parameters.csv")
d <- rbind(fread("https://raw.githubusercontent.com/johnsug/wt/master/recent_wt.csv"), 
           fread("https://raw.githubusercontent.com/johnsug/wt/master/archived_wt.csv"))
d$Date <- as.Date(d$Date, format="%m/%d/%Y")
## impute missing values
frame <- data.table(Date=as.Date(d$Date[dim(d)[1]]:d$Date[1], origin="1970-01-01"))
d <- data.table(left_join(frame, d))
d[, Int:=round(na_interpolation(d$Weight, option="linear"),1)]
d[, Rolling:=frollmean(Int, n=as.numeric(mp[parameter=="interpolation_n", value]), fill=NA)]
d$Year <- as.numeric(substr(d$Date,1,4))
recent <- d[Date==max(Date)]
## join race dates
races <- data.table(fread("https://raw.githubusercontent.com/johnsug/wt/master/event_log.csv"))
races$Date <- lubridate::as_date(races$Date)
races <- races
d <- data.table(left_join(d, races))[Date > mp[parameter=="start_date", value]]

# plots ##########################################################################################

##lm, glm, gam, loess, rlm
output$wt_plot <- renderPlot({
  ggplot(d, aes(x=Date, y=Int, label=Race)) + 
    # plot and smooth weight
    geom_point(aes(x=Date, y=Weight), 
               color=mp[parameter=="point_color", value], 
               size=as.numeric(mp[parameter=="point_size", value]), 
               alpha=as.numeric(mp[parameter=="point_alpha", value])) + 
    geom_smooth(data=d, 
                color=mp[parameter=="smooth_color", value], 
                fill=mp[parameter=="smooth_fill", value], 
                method=mp[parameter=="smooth_method", value], 
                alpha=as.numeric(mp[parameter=="smooth_alpha", value]), 
                size=as.numeric(mp[parameter=="smooth_size", value]), 
                span=as.numeric(mp[parameter=="smooth_span", value])) + 
    # reference points/lines/text
    geom_point(data=d[!is.na(Race)], aes(x=Date, y=Int), 
               size=as.numeric(mp[parameter=="race_size", value]), 
               alpha=as.numeric(mp[parameter=="race_alpha", value])) + 
    geom_hline(yintercept=recent$Weight, 
               color=mp[parameter=="hline_color", value], 
               size=as.numeric(mp[parameter==
                                    "hline_size", value]), 
               alpha=as.numeric(mp[parameter=="hline_alpha", value])) + 
    geom_text(angle=as.numeric(mp[parameter=="race_name_angle", value]), 
              hjust=as.numeric(mp[parameter=="race_name_hjust", value]), 
              alpha=as.numeric(mp[parameter=="race_name_alpha", value])) + 
    # misc formatting
    labs(x="", y="Weight") + 
    theme_minimal()
})

```

Row {data-height=250}
---------------------------------------
  
### Rolling Weight Loss
```{r}
plotOutput("wt_plot")
```
